vobsub: fix loading with url and non-ascii path
mpv-player/mpv pull request #10862
Opened 2022-11-13 21:46 UTC by sarnex

When dragging a vobsub idx file onto the mpv window, the file will be a URL, such as file:///path/to/subs.idx

MPV then tries to guess the corressponding vobsub sub file for that idx file, and then passes that guess to ffmpeg.

ffmpeg then internally removes the file:// prefix and does a open() call.

The problem occurs if the URL contains non-ASCII characters where we see percent encoding. The URL is not decoded and passed to ffmpeg directly, so ffmpeg tries to open /path/to/%E5%A4%A9/subs.idx which obviously doesnt exist.

If we know the vobsub idx file path is a URL, update the filename we use for the vobsub sub file guess to use the decoded path to the vobsub idx file

Fixes https://github.com/mpv-player/mpv/issues/10860

Signed-off-by: Nick Sarnie <sarnex@gentoo.org>

2022-11-24 00:07 UTC, sarnex commented
@N-R-K So yes, I will try to change ffmpeg and see if the maintainers accept that, for anyone that cares it happens here:

```
static int file_open(URLContext *h, const char *filename, int flags)
{
    FileContext *c = h->priv_data;
    int access;
    int fd;
    struct stat st;

    av_strstart(filename, "file:", &filename);
    ```

But right now there is an inconsistent between the format of the filename passed to ffmpeg for the idx vs the sub file.

The idx file is percent decoded by mpv before passing to ffmpeg here in stream_file.c

```
if (!strict_fs) {
        char *fn = mp_file_url_to_filename(stream, bstr0(stream->url));
        if (fn)
            filename = stream->path = fn;
        url = stream->url;
    }
```

But it's never decoded by mpv for the idx file, which is what this PR adds.

Like I said I will do a PR for ffmpeg as well, but I still hope this patch is accepted to make things consistent for the idx/sub file on the mpv/ffmpeg layer

2022-11-24 18:41 UTC, sarnex commented
Note: ffmpeg refused the patch on their end and instead want to introduce fs:// outside of file://, so we need this patch to fix mpv

http://ffmpeg.org/pipermail/ffmpeg-devel/2022-November/304234.html

2024-05-07 10:17 UTC, kasper93 requested changes

2024-05-07 10:17 UTC, kasper93 commented on demux/demux_lavf.c
> +	    bfilename = bstr0(mp_file_get_path(tmp, bfilename));
This will fail if file is not local.

(also use spaces)

2026-07-02 04:18 UTC, Dudemanguy commented
Closing some very old PRs that seemed to stall out. Feel free to complain if you intend to work on it.

2026-07-02 04:18 UTC, closed without merging