ffmpeg: increase minimum required version to 5.1
mpv-player/mpv pull request #10939
Opened 2022-11-27 20:00 UTC by philipl

Now that 0.35 has been released, we can consider increasing our minimum required ffmpeg version. And, as 5.0 has ended up being bypassed by essentially all the major distros, we can go straight to 5.1

This allows us to remove a bunch of conditionals and add proper handling for new deprecations.

I have not handled av_init_packet in this change as it's more involved and I want us to decide we want to do the version bump before putting in that work.

* Fedora 36 shipped with 5.0, but it will be EOL on 2023-05-16, which is almost certainly before we do our next release.

2022-11-27 20:06 UTC, sfan5 commented
what's your plan for `av_init_packet`? there's no single obvious way and getting rid of it requires structural changes.

Also worth mentioning that this means mpv will not build anymore with the forks floating around that have v4l2-requests or v4lm2m support (IIRC those are on 4.4).

2022-11-27 20:08 UTC, CounterPillow commented
> Also worth mentioning that this means mpv will not build anymore with the forks floating around that have v4l2-requests or v4lm2m support (IIRC those are on 4.4).

Don't you worry, instead of upstreaming it, people keep making new branches to shamble on
https://github.com/jernejsk/FFmpeg/tree/v4l2-request-n5.1.2

2022-11-27 20:11 UTC, philipl commented
@sfan5 The only way to fix av_init_packet is to make our function return the dynamically allocated packet and have that propagate out as far as it has to. Maybe that's huge, but it has to be done at some point.

2022-11-27 20:18 UTC, sfan5 commented
> The only way to fix av_init_packet is to make our function return the dynamically allocated packet and have that propagate out as far as it has to. Maybe that's huge, but it has to be done at some point.

No that's easy, but it causes too many allocations/frees which is why wm4 rejected that when I PR'd it years ago. Check the callers of `mp_set_av_packet`.

2022-11-27 21:26 UTC, philipl commented
@sfan5 How serious of a problem do you reckon that actually is? If we simply can't do that many allocations, we'd need something like a new ffmpeg call to reinitialize an already-allocated packet so we can allocate them once and reuse.

2022-11-27 21:29 UTC, philipl commented
It looks like `av_packet_unref` does that. So in theory, we allocate a new packet once in each relevant place we currently have an `AVPacket` and `av_packet_unref` everywhere we do `av_packet_init` today. Does that sound credible?

2022-11-28 04:11 UTC, philipl commented
Dropped down to 4.4

2022-11-28 10:37 UTC, sfan5 commented
> Does that sound credible?

Sure.

2022-11-28 19:44 UTC, philipl commented
I don't plan on reworking `av_init_packet` in this change. Will look at it separately.

2022-11-29 08:41 UTC, sfan5 approved these changes

2022-11-29 08:42 UTC, sfan5 requested changes

2022-11-29 08:42 UTC, sfan5 commented on video/sws_utils.c
> +#else
nvm, this should be in a separate commit

2022-11-29 19:26 UTC, philipl commented
I've split the changes to add new deprecation handling to separate commits

2022-11-29 19:35 UTC, Dudemanguy commented
You forgot to bump the versions in waf.

2022-11-29 23:08 UTC, philipl commented
Added waf changes.

2022-12-01 18:45 UTC, merged