demux_mkv: support ARIB captions
mpv-player/mpv pull request #11235
Opened 2023-01-29 23:18 UTC by rcombs

As per the newly-merged spec. Nothing too complex here, though it does need an `AVCodecParameters` to set the profile + some wrapping to make sure it gets freed.

2023-03-04 16:10 UTC, jeeb requested changes
The actual component tag and data component id checks are pretty much what I wrote in FFmpeg's MPEG-TS demuxer, so in general this looks LGTM.

2023-03-04 16:10 UTC, jeeb commented on demux/demux_mkv.c
> +    if (p)
Destructor only gets registered when after the talloc, so probably this nullptr check is not required.

2023-03-04 16:10 UTC, jeeb commented on demux/demux_mkv.c
> +        if (!lav)
`talloc_ptrtype -> ta_xnew_ptrtype -> ta_oom_g(ta_new_ptrtype(__VA_ARGS__)) `
so I think unless the ta_ stuff somehow gets overridden by something this check should never fail.

2023-03-04 16:10 UTC, jeeb commented on demux/demux_mkv.c
> +    if (!strcmp(sh->codec->codec, "arib_caption")) {
Right after this if, you should probably check if `private_size` contains at least three bytes.

2023-03-04 16:10 UTC, jeeb commented on demux/demux_mkv.c
> +        if (!sh->codec->lav_codecpar)
If we follow the classic mpv OOM handling style, probably `MP_HANDLE_OOM(*lav)`.

I would also recommend taking a pointer towards the codecpar to not have to have `sh->codec->lav_codecpar->` everywhere as it's poked in multiple spots?

2023-03-04 16:10 UTC, jeeb commented on demux/demux_mkv.c
> +        track->private_size = 0;
I don't see this in the audio path? I know the muxers generally don't utilize this data, but why free it? Especially if it was just set to `sh->codec->extradata = track->private_data` before the codec name check, and thus that side might become an invalid pointer if it's just freed here?

2023-03-10 22:22 UTC, rcombs commented
Applied all suggested changes.

2023-03-14 20:32 UTC, jeeb approved these changes

2023-03-14 20:32 UTC, merged