ao_avfoundation: added ao driver with AirPlay support
mpv-player/mpv pull request #11488
Opened 2023-03-22 03:54 UTC by gazsiazasz

Requires tvOS 11.0, watchOS 4.0, iOS 11.0, macOS 10.13 It has also spatial audio on supported models

Based on @tmm1's work

2023-03-22 17:41 UTC, tmm1 commented
I believe @rcombs also revived a version of this driver.

2023-03-22 17:57 UTC, rcombs requested changes
I have a similar branch at https://github.com/rcombs/mpv/tree/avfoundation that's still experimental (due to some startup issues that your branch might have fixed; I'll take a look later). Mine also has some additional functionality for eac3 atmos, along with better OS version targeting handling. Hopefully we can get the differences reconciled.

2023-03-22 22:39 UTC, gazsiazasz commented on audio/out/ao_avfoundation.m
> +    if (@available(tvOS 11.0, watchOS 4.0, iOS 11.0, macOS 10.13, *)) {
Increased availability version numbers and added checks.
I don't have currently any working S/PDIF capable Mac at hand so I didn't dig too much into that.

2023-04-19 18:45 UTC, MaddTheSane commented
Any update on this?

2023-04-19 21:12 UTC, rcombs reviewed
Just realized I had some comments laying around that I'd forgotten to send.

2023-04-20 14:12 UTC, gazsiazasz commented
"You don't need S/PDIF or HDMI output; if you pass E-AC-3 with Atmos to AVFoundation, it'll get spatialized on AirPods with head tracking."

It gets spatialized without any tricks if the input is multi-channel.

2023-04-20 14:19 UTC, gazsiazasz commented on audio/out/ao.c
> +        &audio_out_avfoundation,
corrected the indentation

2023-09-01 15:47 UTC, gazsiazasz commented on audio/out/ao_avfoundation.m
> +    if (@available(tvOS 11.0, watchOS 4.0, iOS 11.0, macOS 10.13, *)) {
It gets spatialized without any tricks if the input is multi-channel.

2023-09-01 16:03 UTC, gazsiazasz commented
@tmm1 please assign another reviewer, @rcombs seems dead :(

2023-09-01 16:59 UTC, rcombs commented
Not dead, just laid off from the job I'd been working on this area at.

2024-03-29 12:48 UTC, Akemi commented
closing this in favour of #11955.

2024-03-29 12:48 UTC, closed without merging