context_angle: include eglext_angle.h explicitly
mpv-player/mpv pull request #11525
Opened 2023-03-30 12:17 UTC by kasper93

Recent MSYS update switched to using vanilla EGL headers, which doesn't include eglext_angle.h implicitly.

2023-03-30 19:13 UTC, jeeb commented
Thanks for looking into this, I actually wondered if this should be a supported configuration since the only difference between standard `<EGL/eglext.h>` and the one in ANGLE was literally just the additional implicit include. I then tried to build it with such a mix where eglext vas vanilla and then the ANGLE file was brought in from its own repository, and noticed it failing at the same bit where you found it to fail during compilation while configure step would succeed.

I did ask around whether such implicit inclusion was common or not in custom EGL extension usage, but basically got no clear answer, so I was kind of planning on posting something similar myself :) .

2023-03-30 19:18 UTC, jeeb requested changes
I would still keep the check for `EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE` to make sure that the EGL header itself is good enough, as that is the base definition of the extension and it is only referenced in `EGL/eglext.h`.

In waf this should be pretty simple by just `int x = EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE; PFNEGLCREATEDEVICEANGLEPROC y = NULL`, but not sure if meson lets you easily do this without doing 2x `cc.has_header_symbol`.

Otherwise totally LGTM :) .

2023-04-02 18:25 UTC, jeeb approved these changes

2023-04-02 18:41 UTC, merged

2023-04-03 18:32 UTC, kasper93 commented
@jeeb thanks for improving the patch. I was not at my dev pc for most part, wanted to get into fixing this pr later.