win32: explicitly guard dark mode calls by Windows version
mpv-player/mpv pull request #11613
Opened 2023-04-22 12:43 UTC by kasper93

In theory it shouldn't be needed, but apparently on Windows 7 those ordinals returns pointers to not executable code trigerring DEP.

Fixes: #11610
Fixes: 9feeb324eddd9ed73ae667e10275f663d70f7544

2023-04-23 22:00 UTC, jeeb requested changes
Might make sense to look into limiting dark mode a bit more than just Win10 generically looking at uxtheme nr135 being different with earlier versions of Win10 :) .

2023-04-24 00:16 UTC, kasper93 commented on video/out/w32_common.c
> +    HMODULE uxtheme_dll = !IsWindows10OrGreater() ? NULL :
done

2023-08-03 20:16 UTC, Jj0YzL5nvJ approved these changes
This looks ready, what's holding it up?

2023-08-05 15:11 UTC, Dudemanguy commented
>This looks ready, what's holding it up?

Nobody knowing anything about windows. Looks OK I guess?

2023-08-05 20:01 UTC, kasper93 commented
I think @jeeb wanted to not use `RtlGetNtVersionNumbers`, but I don't have nicer way to check the version. Doing file version is a lot of unnecessary boilerplate code.

2023-09-21 19:40 UTC, merged