vo_gpu_next: allow to use ICC profile luminance value
mpv-player/mpv pull request #11618
Opened 2023-04-23 20:51 UTC by kasper93

Also while at it respect target-peak option for ICC profile.

Fixes #11449

2023-04-23 20:52 UTC, kasper93 commented
/CC @haasn

2023-04-27 08:06 UTC, haasn requested changes
Missing entry in `DOCS/interface-changes.md`, otherwise good 👍🏻

2023-04-27 16:00 UTC, kasper93 commented
> Missing entry in DOCS/interface-changes.md, otherwise good 👍🏻

Updated. Let me know if the wording is ok.

2023-05-01 12:27 UTC, haasn approved these changes

2023-05-12 20:34 UTC, Traneptora commented
Can we go ahead and merge this?

2023-05-13 15:08 UTC, merged