lua: script_parse_json increase max_depth to 50
mpv-player/mpv pull request #11899
Opened 2023-07-07 19:50 UTC by cvzi

This change allows decoding deeper nested JSON with `utils.parse_json()` from Lua scripts.

I have no clue if 50 is a good or bad value. There seems to be no information why it was set to 32. I set the value to 50 because that value is used here as well:
https://github.com/mpv-player/mpv/blob/6ed521fd14a4cb3ac5bcf69610a8b30fc44facb0/input/ipc.c#L129

**I did not compile nor test this change.**

---
My use-case:
I want to decode the JSON data that is embedded in the Youtube website. This worked until a few days ago. But now the JSON data got bigger (deeper nested/JSON tree has more levels) and the current value 32 is not enough. I tested it with a few Youtube videos and it seems 36 would be enough for my use-case as well. [Related issue in my lua script](https://github.com/cvzi/mpv-youtube-upnext/issues/31).

2023-07-07 21:03 UTC, Dudemanguy approved these changes
Sure if it solves a real problem I don't see why not. I'd just suggest changing to commit message to `lua: increase max depth of parse_json to 50`. Reads better imo.

2023-07-07 21:41 UTC, cvzi commented
Thanks, I changed the commit message as suggested

2023-07-07 22:11 UTC, Dudemanguy requested changes
Sorry for changing the scope on you all of a sudden, but after thinking it over, I think we should unify the json_parse depth everywhere in the code. I've just realized that the tests have a _different_ number (10). How about adding a `MAX_JSON_DEPTH` define in `json.h`, set that to 50, and then use that for every `json_parse` code. That way if we ever need to change it again in the future, it's just one number.

2023-07-08 00:00 UTC, Dudemanguy approved these changes
Thanks, that's exactly what I had in mind.

2023-07-08 01:47 UTC, avih commented
If it needs to support depth 36 today (for one known use case) then IMHO 50 is too little, because it doesn't leave a lot of room for growth before it becomes a limit again.

I'd say it needs to be at least twice the known practical limit, possibly more.

Another factor to consider is that the depth value also limits the C-code recursion depth, and the max recursion depth depends on the stack size and how much each recursive iteration adds to the stack.

I don't recall whether mpv overrides the default stack size, but if not, then using musl-libc it can be quite smaller than with glibc, IIRC around 80K stack with musl vs about 2M (or 8M ?) stack with glibc.

So preferably we also know what's the practical depth limit here before the C-code stack overflows, and keep a bit of room from that side too.

And if they clash (e.g. if JSON depth of 50 results in stack overflows with musl), then maybe increasing the depth is not a good solution.

2023-07-08 03:43 UTC, Dudemanguy commented
>e.g. if JSON depth of 50 results in stack overflows with musl

I did a quick test using the massive chunk of data in OP's linked issue. I artificially extended the depth all the way to 50 while of course changing the recursion depth. It worked perfectly fine and this was while my memory was being eating since firefox is compiling in the background right now. If musl really can't handle this, it's got way bigger problems. Anyways, 50 is only chosen because that already exists in the IPC code. I mean I guess the lua node technically takes more memory than IPC, but there's no way that matters at this level.

Anyways if you or I want to benchmark the ideal depth for parsing json later that's perfectly fine (doing another commit later costs nothing but time), but I don't think OP needs to worry about that. As it is this, this PR does two things that I think are valuable:
1. Unify the JSON recursion to one number.
2. Solves a real-world problem in the process.

2023-07-08 06:15 UTC, N-R-K commented
> So preferably we also know what's the practical depth limit here before the C-code stack overflows, and keep a bit of room from that side too.

Mayhaps the better solution would be to encode the state into an explicit stack instead of having to worry about platform specific limits. Haven't taken too deep of a look into the code to gauge how much work it'd be, but if it's not too much, then IMO it's the better option.

2023-07-08 07:05 UTC, sfan5 approved these changes

2023-07-08 08:17 UTC, avih commented
> 50 is only chosen because that already exists in the IPC code

Thanks, I missed that fact. and it does make some difference.

But still, if we know 36 exists today, then 50 only has 14 additional levels before it becomes a limit again, which is too little IMHO.

> If musl really can't handle this (I'm on glibc), it's got way bigger problems

musl is fairly established, it's fairly easy to increase the depth till it's too much for both musl and glibc, and there's nothing particular with the number 50 which makes it "it really should work with such depth" more than 20 or 200. It comes down to the default stack, and how much an algorithm (ab)uses it.

What if we knew there exists JSON with depth 500 in the wild which we want to support? Would you equally dismiss it as "should be fine"? if not, what's the threshold between "it's fine" and "we should be careful with the stack here"?

Anyway, to be fair, I think 50 or 72 would be fine as far as the stack goes, because both the JSON parser and the lua table construction don't seem to use a lot of stack in each recursive iteration.

It's just that such recursion depths start raising alarms for me.

> if you or I want to benchmark the ideal depth

I don't have a setup to test what's the maximum depth here with musl.

> Unify the JSON recursion to one number.

Depends on the goal of the limit. If it's to avoid stack overflow then sure, it should be the same for all call sites, but if it's to prevent some unreasonably big inputs for whatever reason, then "reasonable" might differ between use cases.

> Mayhaps the better solution would be to encode the state into an explicit stack

Sure. But working code exists, and a refactor carries risks, so it's probably useful to get some numbers and assess the value before a rewrite. If the limit is 500 then it's probably not worth a rewrite, but if it's less than 100 (unlikely IMO) then it could be worth it because the code would be flirting with the limit already today (at the IPC code).

2023-07-08 08:43 UTC, avih commented
On second thought, 50 is fine.

It covers the needs we're aware of (36), and we already have code which uses 50 as a limit, so this doesn't introduce a new potential for stack overflow at the JSON parser.

Maybe we'd need to consider it the next time we'd want to increase it, but for now it's fine.

2023-07-08 08:50 UTC, N-R-K commented
> so it's probably useful to get some numbers and assess the value before a rewrite.

On -O0 (worst case) I get the following with gcc 12.1 (obtained via `gcc -c -o /dev/null misc/json.c -I . -fstack-usage -O0`):

```
./misc/bstr.h:59:27:bstr0                48    static
./misc/ctype.h:10:19:mp_isupper          16    static
./misc/ctype.h:11:19:mp_islower          16    static
./misc/ctype.h:12:19:mp_isdigit          16    static
./misc/ctype.h:13:19:mp_isalpha          24    static
./misc/ctype.h:14:19:mp_isalnum          24    static
misc/json.c:57:13:eat_c                  16    static
misc/json.c:66:13:eat_ws                 16    static
misc/json.c:76:6:json_skip_whitespace    24    static
misc/json.c:81:12:read_id                64    static
misc/json.c:99:12:read_str              112    static
misc/json.c:133:12:read_sub              96    static
misc/json.c:187:5:json_parse             96    static
```

This doesn't not include stack usage of called functions though. But in this case only `read_sub` calls `json_parse` recursively.

So 50 recursive calls would roughly take `(96+96)*50 + 256 = 9856` bytes (adding a bit of headroom of 256 bytes for the other calls eg. strcmp, eat_ws etc) or roughly 10KiB. (With -O1 it's roughly 6KiB).

If stack size really is 80K on certain platforms, 10KiB way too close IMO, since we don't know how much the caller is using.

If a refactor using explicit stack isn't an option, then I'd try to set a higher reasonable stack size to be on the safe side.

2023-07-08 09:24 UTC, avih commented
> If stack size really is 80K on certain platforms

Nearly. From here: https://wiki.musl-libc.org/functional-differences-from-glibc.html

> musl provides a default thread stack size of 128k (80k prior to 1.1.21)

As for
> 10KiB way too close IMO, since we don't know how much the caller is using.

I'd think it's still OK, because it's an order of magnitude less than the maximum 127K. but yeah, it's not very far either.

Anyway, for now I think 50 is a pure win because it increases the limit without additional potential risk.

But we'd probably need to reconsider if we need to raise the limit again.

2023-07-08 09:36 UTC, merged

2023-07-08 10:26 UTC, avih commented
Also, for future reference, unlimited JSON parsers (up to heap OOM) are available for lua, like this small one https://github.com/rxi/json.lua (280 LOC).

2023-07-08 10:40 UTC, N-R-K commented
> Also, for future reference, unlimited JSON parsers (up to heap OOM) are available for lua, like this small one https://github.com/rxi/json.lua (280 LOC).

Just FYI: the json parser in `misc/json.c` allows for some non-standard extensions. So other json parsers most likely aren't going to be a drop in replacements.