path-unix: Only accept absolute paths
mpv-player/mpv pull request #12258
Opened 2023-08-26 14:17 UTC by linkmauve

The XDG Base Directory specification says “All paths set in these environment variables must be absolute. If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.”

2023-08-26 17:09 UTC, philipl reviewed
Should we log something so there's feedback?

2023-08-26 20:00 UTC, N-R-K commented
> Should we log something so there's feedback?

You can't (not without doing hacky shit) since `pthread_once` doesn't accept a context pointer.  There was a discussion about the same issue here: https://github.com/mpv-player/mpv/pull/12135#discussion_r1291730725

2023-08-26 20:11 UTC, N-R-K requested changes

2023-08-26 20:11 UTC, N-R-K commented on osdep/path-unix.c
> +    if (home && home[0] == '/')
This doesn't look right. `$HOME` is not part of XDG base dirs.

Same with all the other `home[0] == '/'` cases.

2025-10-01 10:00 UTC, linkmauve commented on osdep/path-unix.c
> +    if (home && home[0] == '/')
Does that mean programs should happily accept a relative `HOME`?

(Sorry for having dropped the ball on this PR for two years, I’ll get back to it shortly.)

Edit: This is now fixed, we accept relative `HOME` again with this PR.

2026-07-02 04:31 UTC, Dudemanguy requested changes
There's one more `xdg_config[0]` that popped up in here and now needs a check since the last time I looked at this. The rest looks good.

2026-07-02 07:48 UTC, linkmauve commented
There, I changed that in `path-darwin.c` as well.

2026-07-02 13:32 UTC, Dudemanguy reviewed
Thanks LGTM

2026-07-02 17:21 UTC, Dudemanguy approved these changes

2026-07-02 17:36 UTC, merged