vo: change vsync_interval to double
mpv-player/mpv pull request #12356
Opened 2023-09-08 02:54 UTC by Dudemanguy

So strangely enough, estimated_vsync_interval is stored as a double but nominal_vsync_interval is not and neither is the vsync_interval. Those are stored as int64_t. This loss of precision can matter even in common cases. For instance, take a typical 60 Hz monitor. Instead of 16666.6666 (repeating) being calculated as the vsync interval, you'll get 16666 since the decimals are truncated. This is not really good at all and affects the calculated speed values you get when using display sync. For consistency and better precision, these should all be doubles just like estimated_vsync_interval. Technically this means that we won't be able to store as high of an integer value but such values would be absurdly huge and never actually needed. Also estimated_vsync_interval already can't handle such a case anyway.

2023-09-08 03:48 UTC, christoph-heinrich requested changes
You're not actually touching that here, but it's related: `vsync_stddef()` needs to take a double.

Also I personally don't really care, but since I noticed:
["Use present tense to describe the situation with the patch applied, and past tense for the situation before the change."](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#write-good-commit-messages)

2023-09-08 03:57 UTC, Dudemanguy commented
>You're not actually touching that here, but it's related: vsync_stddef() needs to take a double.

Ah good catch. Missed that one.

>Use present tense to describe the situation with the patch applied

That's exactly what I'm doing?

2023-09-08 04:02 UTC, christoph-heinrich commented
> That's exactly what I'm doing?

Then I must be misunderstanding something, because it seems to me like you're describing the situation before the change in present tense.

2023-09-08 04:11 UTC, christoph-heinrich approved these changes

2023-09-08 10:47 UTC, DanOscarsson commented
While I have not had problem with microsecond resolution in calculations, only in places with millisecond resolution.
But in many systems nanoseconds are used. For example vdpau and Linux kernel.
Why not change all time handling in mpv to nanoseconds (int64_t)?
Now some are float, double, different type of ints, and sometimes seconds, or milliseconds or microseconds.
Always using nanoseconds would be easier with less conversions and less change of making mistakes with time units.

2023-09-08 11:17 UTC, kasper93 commented
If you change it to double, you should also remove the `1e6` multiplication that was done for base change. And few more things need to be adjusted like mentioned by @christoph-heinrich `vsync_stddef`

2023-09-08 13:24 UTC, Dudemanguy commented
>Why not change all time handling in mpv to nanoseconds (int64_t)?

That would be a massive change. And even then, you still would want to use double in a few places so division isn't truncated.

>If you change it to double, you should also remove the 1e6 multiplication that was done for base change. And few more things need to be adjusted like mentioned by @christoph-heinrich vsync_stddef

What do you mean? 1e6 is the conversion factor. You still need it.

2023-09-08 16:23 UTC, kasper93 commented
> What do you mean? 1e6 is the conversion factor. You still need it.

2023-09-08 16:27 UTC, kasper93 commented
> What do you mean? 1e6 is the conversion factor. You still need it.

This factor is only added to be able to store the `0.016666666666666666` in integer as `16666`. If we are using double there is not need to multiply it, only to divide later. Of course this has to be also changed to double in `vsync_samples`, `vsync_stddef` and so on. But no need to multiply it.

2023-09-08 16:43 UTC, kasper93 commented
> > Why not change all time handling in mpv to nanoseconds (int64_t)?
> 
> That would be a massive change. And even then, you still would want to use double in a few places so division isn't truncated.

If you divide nanosecond values, truncation is fine. No need for sub-nanosecond precision.

> That would be a massive change.

Changing everywhere, sure. But in this particular case it is just changing this hardcoded `1e6` to `1e9` :)

But I would still be consistend, either we use double seconds or int64_t nanoseconds. No in between.

2023-09-08 18:08 UTC, Dudemanguy commented
>This factor is only added to be able to store the 0.016666666666666666 in integer as 16666

I mean sure that was probably the original reasoning, but `estimated_vsync_interval`, `nominal_vsync_interval`, and `vsync_interval` are all microseconds so you need the 1e6 conversion. I mean I could change it to be some other unit if you really insist, but that becomes a different change and I have to make sure all calculations being done are with the correct units, etc.

>Of course this has to be also changed to double in vsync_samples

vsync_samples actually is an integer. The value (provided mpv doesn't make up something from mp_time_us) comes from presentation feedback from the OS. I didn't look at what windows does, but xorg and wayland report presentation times as 64 bit integers. Of course, this could be changed to doubles anyway but it would make no difference.

>If you divide nanosecond values, truncation is fine. No need for sub-nanosecond precision.

Well it's true that the precision loss probably doesn't matter in this case, but I would still prefer using a double over in64_t nanoseconds because it's the same storage size (well on common platforms anyway; dunno if it's different on other architectures) and is more accurate.

>But I would still be consistent, either we use double seconds or int64_t microseconds. No in between.

The units are double microseconds. All I'm changing is the storage type here.

2023-09-08 18:27 UTC, kasper93 commented
> I mean sure that was probably the original reasoning, but estimated_vsync_interval, nominal_vsync_interval, and vsync_interval are all microseconds so you need the 1e6 conversion. I mean I could change it to be some other unit if you really insist, but that becomes a different change and I have to make sure all calculations being done are with the correct units, etc.

What is the point of this change if they same conversion and "precision loss" is done just in a different place?

> Well it's true that the precision loss probably doesn't matter in this case, but I would still prefer using a double over in64_t nanoseconds because it's the same storage size

Using integers have the advantage on fixed precision that you need. You don't have weird floating point errors and so on. It is different thing. You generally don't want to mix integer and doubles. It is design decision you made once, that time stamp are in this specific format, with this specific precision and write the code to properly handle that.

2023-09-08 18:44 UTC, Dudemanguy commented
>What is the point of this change if they same conversion and "precision loss" is done just in a different place?

What? The only error is floating point error which is much less than the current truncation in master. I don't understand what you're trying to suggest here. E.g. `nominal_vsync_interval` comes from the display fps and thus requires a division. There's no way around that short of completely altering how we store that value (say using AVRational or something).

>You generally don't want to mix integer and doubles.

mpv already does this in several places. I didn't start it. Just look at `player/video.c` and `vo/vo.c`.

2023-09-08 19:52 UTC, kasper93 commented
> I don't understand what you're trying to suggest here. E.g. nominal_vsync_interval comes from the display fps and thus requires a division. There's no way around that short of completely altering how we store that value (say using AVRational or something).

Inversion is fine. I only argue that after switching to double you no longer need to store those values in microseconds, because you can simply keep them in seconds. 

Which is what `vo_get_estimated_vsync_interval` expects. And all things connects.
```
double vo_get_estimated_vsync_interval(struct vo *vo)
{
    struct vo_internal *in = vo->in;
    pthread_mutex_lock(&in->lock);
    double res = in->estimated_vsync_interval / 1e6;
    pthread_mutex_unlock(&in->lock);
    return res;
}
```

> mpv already does this in several places. I didn't start it. Just look at player/video.c and video/out/vo.c.

Nah, don't worry. I'm not saying to change everything ;p

2023-09-08 20:42 UTC, Dudemanguy commented
>Inversion is fine. I only argue that after switching to double you no longer need to store those values in microseconds, because you can simply keep them in seconds.

You say "simply" but it's not simple. Now several places throughout the code that deals with `in->vsync_interval` and similar will now need additional conversion factors to ensure they working with the same units. You'd eliminate the need for conversion in some places but then other place start converting. I didn't actually attempt to write out the code or anything, but I don't see the benefit. It's just more complication.

>Which is what vo_get_estimated_vsync_interval expects. And all things connects.

That one is an outlier and only used for getting the estimated display fps. Honestly, it's weird imo that the 1e6 division is baked into the function and the conversion is not done in `mp_property_estimated_display_fps` instead.

2023-09-09 01:03 UTC, kasper93 commented
I'm fine with this patch, indeed changing more would require more in-depth changes. Probably not needed.

2023-09-09 02:48 UTC, merged