Update ytdl_hook.lua: Fix yt-dlp's Incomplete data received error which is rather non-critical to catch
mpv-player/mpv pull request #12511
Opened 2023-09-28 07:35 UTC by GunGunGun

Because `Incomplete data received` isn't critical, should only check if json is blank.

Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

2023-09-28 19:29 UTC, Earnestly commented
Can confirm this PR solves the very same issue I was experiencing recently; tested on commit https://github.com/mpv-player/mpv/commit/f9234d890aab3bf0f959b79ec2b7843b6c9610d8.

2023-09-28 19:50 UTC, christoph-heinrich commented
yt-dlp also returns non zero status codes for other non critical errors, but some of those cases can result in not all playlist entries getting listed, and the way it is now there is no feedback that there even is something that wasn't fully successful.

Have you looked at the specific status code? Maybe we can react differently to different status codes.

2023-09-28 22:24 UTC, krasnh commented
This solved the problem with YouTube playlists.

2023-09-29 02:52 UTC, GunGunGun commented
@christoph-heinrich 

> Have you looked at the specific status code? Maybe we can react differently to different status codes.

I debugged it quite a bit `result.status = 1` in this case.

Full result logging if you want it:

```
[ytdl_hook] status: 1
[ytdl_hook] reason:
[ytdl_hook] stdout: {"id": "PLVM1qRtVEeErISdPLpYEc53XEHU5m34cl", "title": "Let's Play Symphony of War: Nephilim Saga", "availability": "public", "channel_follower_count": null, "description": "", "tags": [], "thumbnails": [{"url": "https://i.ytimg.com/vi/D0wjqctK9KQ/hqdefault.jpg?sqp=-[STRIPPED_CUZ_USELESS]....
[ytdl_hook]
[ytdl_hook] stderr: ERROR: Incomplete data received
[ytdl_hook]
[ytdl_hook] ERROR: Incomplete data received
[ytdl_hook] youtube-dl failed: unexpected error occurred

```

2023-09-29 03:51 UTC, christoph-heinrich commented
> I debugged it quite a bit `result.status = 1` in this case.

No surprise there, considering the exit codes I linked.

I still don't like that the error gets completely ignored now. We should at least print a warning with stderr when `status~=0` but the json is still usable.

2023-09-29 06:47 UTC, GunGunGun commented
@christoph-heinrich 
> I still don't like that the error gets completely ignored now. We should at least print a warning with stderr and status when `status~=0` but the json is still usable.

How about parsing the JSON first, I'll create a new commit and let's see if it's okay.

2023-09-29 13:20 UTC, christoph-heinrich commented
> @christoph-heinrich
> 
> > I still don't like that the error gets completely ignored now. We should at least print a warning with stderr and status when `status~=0` but the json is still usable.
> 
> How about parsing the JSON first, I'll create a new commit and let's see if it's okay.
> 
> Actually I followed your idea and just print a warning instead.

Hmm...
> at least print a warning with stderr and status

2023-09-29 13:57 UTC, GunGunGun commented
@christoph-heinrich
> at least print a warning with stderr and status

It's done.

2023-09-29 14:30 UTC, po5 commented
Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

2023-09-29 14:46 UTC, christoph-heinrich requested changes
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#write-good-commit-messages
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#always-squash-fixup-commits-when-making-changes-to-pull-requests

The PR template literally says
> Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

>Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

2023-09-29 14:46 UTC, christoph-heinrich commented on player/lua/ytdl_hook.lua
> +    end
```suggestion
    if result.status ~= 0 and json then
        msg.warn("exit status isn't zero but the JSON still parsed successfully")
        msg.warn(result.stderr:match("^%s*(.*)%s*$"))
        msg.verbose("status:", result.status)
        msg.verbose("reason:", result.error_string)
        msg.verbose("stdout:", result.stdout)
        msg.verbose("stderr:", result.stderr)
    end
```

2023-09-30 01:06 UTC, GunGunGun commented
@po5 @christoph-heinrich I see, I've read the guide and thanks!

2023-10-07 04:44 UTC, Dudemanguy commented
Can you please squash your commits?

2023-10-07 05:04 UTC, christoph-heinrich commented
fwiw that specific playlist issue has already been fixed by yt-dlp. It may still make sense to allow parse-able jsons to continue, but I'm worried that it will end up leading to crashes because the json didn't contain fields that are assumed to exist by other parts of the ytdl_hook.

I don't know if such a scenario can actually happen, and technically there is always the possibility of them changing up their json structure, but it's a concern nonetheless.

2023-10-07 05:14 UTC, Dudemanguy commented
Oh I had assumed it was another one of those "the ytdl_hook" is outdated again things. If there's no actually concrete issue this solves anymore, then I don't think we need this? All the concerns you raised are valid and if there's a use case then, we can revisit it later.

2023-10-20 19:34 UTC, closed without merging