another round of nanosecond conversions
mpv-player/mpv pull request #12621
Opened 2023-10-11 20:45 UTC by Dudemanguy

This should be all of it now. The most dangerous conversion here is, of course, the audio ones. I'm only actually able to test jack and pipewire which work fine as far as I can tell. Anyways, I'll let this sit for a while so errors and so on can be spotted (found a couple while opening this PR).

2023-10-11 21:53 UTC, orion1vi commented on audio/out/ao_coreaudio.c
> +    MP_VERBOSE(ao, "device latency [us]: %lld\n", device_latency_ns);
[ns]

2023-10-11 22:01 UTC, Dudemanguy commented on audio/out/ao_coreaudio.c
> +    MP_VERBOSE(ao, "device latency [us]: %lld\n", device_latency_ns);
Always something. Thanks.

2023-10-12 04:22 UTC, orion1vi requested changes

2023-10-12 14:20 UTC, Dudemanguy commented on audio/out/ao_coreaudio_utils.c
> +    return frames / MP_TIME_S_TO_NS(ao->samplerate);
This and the other one return `in64_t` anyways. Also I'm not sure why this ever casted to float seeing as 1e6 should be a double.

2023-10-12 14:31 UTC, orion1vi commented on audio/out/ao_coreaudio_utils.c
> +    return frames / MP_TIME_S_TO_NS(ao->samplerate);
Current change will return 0, look at ao_audiotrack change if you're misunderstanding what I'm suggesting here.

2023-10-12 14:47 UTC, Dudemanguy commented on audio/out/ao_coreaudio_utils.c
> +    return frames / MP_TIME_S_TO_NS(ao->samplerate);
Oh my bad. Order of operations duh.

2023-10-12 14:49 UTC, orion1vi commented on audio/out/ao_jack.c
> +    end_time += (jack_latency + nframes) / (double)MP_TIME_S_TO_NS(ao->samplerate);
Another one of those

2023-10-12 14:57 UTC, Dudemanguy commented on audio/out/ao_jack.c
> +    end_time += (jack_latency + nframes) / (double)MP_TIME_S_TO_NS(ao->samplerate);
Thanks again.

2023-10-16 15:36 UTC, Dudemanguy commented
The past couple of PRs seem to have gone smoothly overall so hopefully this will be the same.

2023-10-16 15:38 UTC, merged