console.lua: complete choice options
mpv-player/mpv pull request #12636
Opened 2023-10-14 19:07 UTC by guidocella

2023-10-21 17:25 UTC, christoph-heinrich commented on player/lua/console.lua
> +    return mp.get_property_native('option-info/' .. option .. '/choices', {})
```suggestion
    local option = mp.get_property_native('option-info/' .. option, {})
    if option.type == 'Flag' then
        return { 'no', 'yes' }
    else
        return option.choices or {}
    end
```

2023-10-21 21:04 UTC, christoph-heinrich requested changes

2023-10-21 21:04 UTC, christoph-heinrich commented on player/lua/console.lua
> +            pattern = '^%s*' .. command .. '%s+"?([%w_-]+)"?%s+"()%g*$',
`%g` doesn't exist in Lua 5.1

2023-10-21 21:51 UTC, christoph-heinrich approved these changes

2023-10-25 15:15 UTC, N-R-K approved these changes

2023-10-25 15:39 UTC, Dudemanguy approved these changes
Nice. Looks good.

2023-10-25 15:42 UTC, merged