meson: remove main function from libmpv build
mpv-player/mpv pull request #13638
Opened 2024-03-05 11:53 UTC by owl0w1

Currently a main function is included in libmpv shared library build, which it doesn't need. This commit makes it so that main function is only included in cplayer build, not libmpv build. This shaves off 560 bytes from libmpv build.

2024-03-05 12:56 UTC, kasper93 commented
Don't we have visibility set to hidden, so not used libraries wouldn't be linked anyway?

2024-03-05 13:41 UTC, kasper93 commented
What if we do this instead?
``` diff
diff --git a/meson.build b/meson.build
index 1eb36a7807..1ccb8b7e06 100644
--- a/meson.build
+++ b/meson.build
@@ -381,6 +381,9 @@ pthread_debug = get_option('pthread-debug').require(
 )
 features += {'pthread-debug': pthread_debug.allowed()}

+flags += ['-ffunction-sections', '-fdata-sections']
+link_flags += ['-Wl,--gc-sections']
+
 add_project_arguments(flags, language: 'c')
 add_project_link_arguments(link_flags, language: ['c', 'objc'])
```

2024-03-05 18:00 UTC, sfan5 commented on meson.build
> +    if get_option('cplayer')
cplayer check here is pointless

2024-03-05 18:23 UTC, kasper93 commented
> This break MinGW GCC. gc-sections are invalidated in BFD COFF, resulting in a nearly 20% increase in binary size. LLD work fine though.

That sounds terrible, is there a bug report for that?

2024-03-05 20:54 UTC, sfan5 commented
IMO those flags are general optimizations that should be left up to the person building mpv and not something we should set by default.

2024-03-06 00:06 UTC, kasper93 commented
> IMO those flags are general optimizations that should be left up to the person building mpv and not something we should set by default.

I see where you coming from, but I don't agree in this case. Those flags changes build behavior, it is not optimization in itself. The way mpv and libmpv is build together makes it not only main() being shared, but not used by the other party. Also by disabling various options and features, we may orphan some functions that may not be ifdefed, because not all common and glue code is ifdefed.


both solutions are ok, gc-sections is more versatile and doesn't introduce more complexity in meson tho.

2024-03-06 04:54 UTC, thesamesam commented
> > > This break MinGW GCC. gc-sections are invalidated in BFD COFF, resulting in a nearly 20% increase in binary size. LLD work fine though.
> > 
> > 
> > That sounds terrible, is there a bug report for that?
> 
> [lovell/sharp-libvips#88 (comment)](https://github.com/lovell/sharp-libvips/pull/88#issuecomment-791326495) [mstorsjo/llvm-mingw#188](https://github.com/mstorsjo/llvm-mingw/issues/188) [reviews.llvm.org/D101568](https://reviews.llvm.org/D101568) Of course, in most cases the increase in binary size will not be so significant. Only fully static build environments will see a 20% regression.

None of those are a Binutils bug report, or what am I missing/misunderstanding?

> IMO those flags are general optimizations that should be left up to the person building mpv and not something we should set by default.

In general, downstreams are reluctant to set these specific flags because whether they're safe to use depends on upstream knowledge about the software layout. Plenty of other software sets it too.

2024-03-06 12:25 UTC, sfan5 commented on meson.build
> +    if get_option('cplayer')
The variable is only used in a section guarded by `if get_option('cplayer')` at the end and there's no harm in setting something that ends up unused,

2024-03-06 20:52 UTC, sfan5 requested changes
looks good but please squash commits

2024-03-07 11:45 UTC, sfan5 approved these changes

2024-03-07 12:39 UTC, closed without merging