terminal: support mouse input
mpv-player/mpv pull request #13711
Opened 2024-03-16 11:15 UTC by na-na-hi

This adds mouse input parsing and enables mouse support for terminal VOs (`vo_tct`, `vo_sixel`, `vo_kitty`), making it possible to use mouse key bindings and OSC with these VOs.

2024-03-16 20:57 UTC, philipl approved these changes

2024-03-22 05:21 UTC, kasper93 commented
Are you interested also in implementing it for win32? There are dragons hiding there, but it should be possible to add support for it.

2024-04-17 21:57 UTC, kasper93 requested changes
Few minor comments.

2024-04-17 21:57 UTC, kasper93 commented on osdep/terminal-unix.c
> +             match->type == ENTRY_TYPE_MOUSE_MOVE) && seq_len >= 6) {
new line before `{` for multi line conditions.

2024-04-17 21:57 UTC, kasper93 commented on osdep/terminal-win.c
> +  HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
You can use `hSTDOUT` define, just for consistency.

2024-04-17 21:57 UTC, kasper93 commented on osdep/terminal-win.c
> +                get_font_size(&w, &h);
Does it make sense to set pos to 0, 0 if this fails?

2024-04-17 21:57 UTC, kasper93 commented on osdep/terminal-win.c
> +    HANDLE in = GetStdHandle(STD_INPUT_HANDLE);
`hSTDIN`

2024-04-17 23:03 UTC, kasper93 approved these changes
Frankly not sure about usefulness of this, but why not.

2024-04-17 23:03 UTC, merged

2024-07-09 21:49 UTC, kasper93 commented on osdep/terminal-win.c
> +    }
@na-na-hi 

This doesn't work well for recently added sixel support in conhost.

They use 10x20 sized cells (see https://github.com/microsoft/terminal/pull/17504).

Do you want to play around with it and improve it?

2024-07-10 15:14 UTC, kasper93 commented on osdep/terminal-win.c
> +    }
> Not sure what's the best way to proceed from here.

Same. Would be nice to have it supported, but don't see easy path forward with this one.