Fix stats conv
mpv-player/mpv pull request #14613
Opened 2024-07-30 00:55 UTC by llyyr

Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

2024-07-30 11:30 UTC, kasper93 commented on TOOLS/stats-conv.py
> +    cur.plot([x for x, _ in e.vals], [y for _, y in e.vals], **args)
maybe
```suggestion
    x_vals, y_vals = zip(*e.vals)
    cur.plot(x_vals, y_vals, **args)
```

2024-07-30 15:15 UTC, llyyr commented on TOOLS/stats-conv.py
> +    cur.plot([x for x, _ in e.vals], [y for _, y in e.vals], **args)
Done

2024-07-31 23:26 UTC, kasper93 commented
Events like `mistimed` are not longer working (being drawn) after those changes.

2024-07-31 23:26 UTC, kasper93 requested changes
Events like mistimed are not longer working (being drawn) after those changes.

2024-07-31 23:51 UTC, llyyr commented
> Events like `mistimed` are not longer working (being drawn) after those changes.

`get_event(name, "event-signal")` and `get_event(event, "event-signal")` looked exactly the same to me 2 days ago...

Fixed.

2024-07-31 23:57 UTC, kasper93 approved these changes
works

2024-07-31 23:58 UTC, merged