demux: reclaim demux_packets to reduce memory allocator pressure
mpv-player/mpv pull request #14955
Opened 2024-09-30 13:59 UTC by kasper93

This update introduces a demux_packet_pool, allowing for the reuse of previously allocated packets when needed.

sizeof(AVPacket) is not a part of the lavc public ABI, which prevents us to allocate memory in larger blocks. However, we can substantially decrease the amount of alloc/free operations during playback by reusing both mpv's demux_packet and AVPacket.

This adjustment addresses the root cause of issue #12076, which, although resolved upstream, did not fully tackle the persistent problem of allocating small blocks of aligned memory. This issue largely stems from the FFmpeg design of the AVPacket API. After this change memory will no longer be allocated once cache limits is reached.

The demux_packet_pool is shared as a global pool of packets for a given MPContext.

This change significantly speeds up the demuxer deinitialization, benefiting file switching scenarios, especially when a large demuxer cache is used.

See: #12294
See: #12563 

I decided to open PR without the "memory leak" part, which were main discussion point in the #12566 and after refinements of the patches, it is not the main objective of this change. Hance, the #12566 is left with the "fast quit" option and here we add demux pool, maybe hopefully we will be able to iterate on those patches this way.

2024-09-30 18:29 UTC, kasper93 commented on demux/demux_mkv.c
> +        struct demux_packet *new = new_demux_packet(demuxer->global->packet_pool, newlen);
Could you explain? I don't know how to do that.

2024-09-30 18:34 UTC, kasper93 commented on demux/demux_mkv.c
> +        struct demux_packet *new = new_demux_packet(demuxer->global->packet_pool, newlen);
I think I know what you mean.

2024-09-30 19:07 UTC, kasper93 commented on demux/packet_pool.h
> +};
Ok.

2024-10-01 00:04 UTC, kasper93 commented on demux/demux_mkv.c
> +        struct demux_packet *new = new_demux_packet(demuxer->global->packet_pool, newlen);
Where such wrapper should reside? Not sure I grasp the gain. Would it be 
``` c
struct packet_pool_ctx {
    struct *packet_pool;
}
```
initialized somwhere(TM)? Would we keep it alongside `global` member in appropriate structs?

2024-10-01 01:55 UTC, kasper93 commented on demux/demux_mkv.c
> +        struct demux_packet *new = new_demux_packet(demuxer->global->packet_pool, newlen);
I tried something, see now if it is ok.

2025-01-02 17:02 UTC, CounterPillow reviewed
Some concurrency concerns but they might be wholly theoretical

2025-01-02 17:02 UTC, CounterPillow commented on demux/packet_pool.c
> +    demux_packet_pool_clear(pool);
Another thread can theoretically try to use the pool between this clear and the `mp_mutex_destroy` (which on Linux is just a "is this locked? No? Okay we good.") I don't know how big of a deal this is, but the destroy might fail because something else is trying to push packets in through the `demux_packet_pool_` functions.

> ***man 3p pthread_mutex_destroy***
> A mutex can be destroyed immediately after it is unlocked. However, since attempting to destroy a locked mutex, or a mutex that another thread is attempting to lock,  or a mutex that is being used in a pthread_cond_timedwait() or pthread_cond_wait() call by  another thread, results in undefined behavior, care must be taken to ensure that no other thread may be referencing the mutex.

The above-suggested "is this okay to use?" member of the pool might make this less scary. One possible solution is to make sure all `demuxer_packet_pool_` functions that touch the lock (and the pool) first check whether the pool is still okay to use *after* acquiring the lock, and the uninit function flips that member to say it's not okay to use it anymore while it holds a lock, so even if it then drops the lock before destroying it, none of the places that can reference the lock will add any more packets into the pool after it is cleared but before the mutex becomes invalid. However, I think you also need to check the return value (and retry based on it) of `mp_mutex_destroy` here on non-Linux platforms where destroying a mutex might actually do something? Not sure.

2025-01-02 17:41 UTC, kasper93 commented on demux/packet_pool.c
> +struct demux_packet_pool {
init/uninit are not thread safe, but they don't meant to be. It is on user to ensure its lifetime. 

> We might want an "initialized" member or something of the sort here.

The fact that the object exist means it is initialized. There is no other way to create the pool, but the _init function which does not return the object it initializes it in  mpv_global.

> where we're trying to destroy a locked mutex

It is usage error and if someone uninits the pool while there might be users of it active it is an error. Many subsystems in mpv works like that, thread_pool, logger, stats and now thread_pool

I don't mind changing that, if you feel it is important, but as with the current use of this pool, I think it is fine as-is in terms of its lifetime.

2025-01-03 08:23 UTC, CounterPillow commented on demux/packet_pool.c
> +struct demux_packet_pool {
Yeah alright, if it follows other mpv conventions and it's up to the code using this to not be dumb here then I'm fine with it and have no problem.

2025-01-21 16:39 UTC, sfan5 requested changes

2025-01-21 16:39 UTC, sfan5 commented on demux/packet_pool.h
> +void demux_packet_pool_uninit(void *p);
no type?

2025-01-21 16:39 UTC, sfan5 commented on filters/filter.c
> +        .packet_pool = demux_packet_pool_get(params->parent ? params->parent->global : params->global),
i don't see why not
```suggestion
        .packet_pool = demux_packet_pool_get(params->global),
```

2025-01-21 16:39 UTC, sfan5 commented on demux/packet_pool.h
> + * linked list while locking the pool to ensure thread safety.
implementation detail 
```suggestion
 * This function frees all the packets in the pool.
```

2025-01-21 16:39 UTC, sfan5 commented on demux/packet_pool.c
> +    mp_mutex_unlock(&pool->lock);
you could take the pointer under lock and then free without lock

2025-01-21 16:39 UTC, sfan5 commented on demux/packet.c
> +        ta_free_children(dp);
so as far as I can see we unref and free what I assume to be buffers that were referenced from the `avpkt`.
since this happens unconditionally shouldn't this happen upon pushing to the pool, to free the memory?

2025-01-26 01:36 UTC, kasper93 commented on demux/packet_pool.h
> +void demux_packet_pool_uninit(void *p);
This is attached directly as dtor in `talloc_set_destructor`. I can remove it from header file and make static instead.

2025-01-26 01:40 UTC, kasper93 commented on demux/packet_pool.h
> + * linked list while locking the pool to ensure thread safety.
Done.

2025-01-26 01:47 UTC, kasper93 commented on demux/packet_pool.c
> +    mp_mutex_unlock(&pool->lock);
Sure, that works, changed. This function in fact will never be used except destroying the pool, so not much change overall.

(side note: I remember having testing async destroying of packets, but in extreme scenarious it was just stalling other thread on memory allocations, because of all the free() that it did.)

2025-01-26 01:59 UTC, kasper93 commented on demux/packet.c
> +        ta_free_children(dp);
This is intended. `packet_create` is called in relatively sane intervals and rate for demuxing a video, we can get the single packet from pool and initialize/clear it before use. What this avoids is the issue where we have huge demuxer cache filled and suddenly we want to "clear all now", this happens on file close for example. In this case we don't want to iterate over all packets and distribute this load over the time while the packets are reused for next playback.

2025-01-26 13:23 UTC, sfan5 commented on demux/packet.c
> +        ta_free_children(dp);
Okay, then I suggest documenting this with comments and moving the freeing to `demux_packet_pool_pop` so that it is documented to return an empty packet with (optionally) an empty avpacket on the side.

2025-01-26 13:26 UTC, sfan5 commented on demux/packet_pool.c
> +    demux_packet_pool_prepend(pool, dp, dp);
another thought I just had: to catch UAF we should have a debug option where the contents of the demux packet are overwritten with some dummy constant (e.g. `0xcc` but not zero) as soon as you push it into the pool

2025-01-26 13:31 UTC, sfan5 commented on demux/packet_pool.c
> +    demux_packet_pool_prepend(pool, dp, dp);
or much simpler and also friendly to ASan: an option that turns the pool into a no-op

2025-01-26 16:57 UTC, kasper93 commented on demux/packet.c
> +        ta_free_children(dp);
Done.

2025-01-26 17:06 UTC, kasper93 commented on demux/packet_pool.c
> +    demux_packet_pool_prepend(pool, dp, dp);
I see where you are coming from. But I would like to avoid runtime options for that. And for compile time, you can just replace `push` body with `free_demux_packet(dp);`.

2025-01-26 17:57 UTC, sfan5 commented on demux/packet_pool.c
> +    demux_packet_pool_prepend(pool, dp, dp);
Of course, not a runtime option. But a compile time option for this should exist. I just don't know how we should name it.

> you can just replace push body with free_demux_packet(dp);.

..and rewrite `prepend` somewhat.
This code should exist already.

But anyway it doesn't have to happen in *this* PR.

2025-01-26 22:11 UTC, kasper93 commented on demux/packet_pool.c
> +    demux_packet_pool_prepend(pool, dp, dp);
Added meson option for disabling packet pool. Still uncertain how useful that might be though.

2025-01-28 13:53 UTC, sfan5 approved these changes
lgtm. will test later.

2025-01-28 13:53 UTC, sfan5 commented on demux/packet_pool.c
> +static void demux_packet_pool_free_packets(struct demux_packet *dp)
personally I'd just call this `free_demux_packets`

2025-01-28 14:50 UTC, kasper93 commented on demux/packet_pool.c
> +static void demux_packet_pool_free_packets(struct demux_packet *dp)
fixed

2025-01-29 18:18 UTC, sfan5 approved these changes
works

2025-02-05 04:09 UTC, kasper93 commented
Hopefully it will be fine, we can always revert.

2025-02-05 04:09 UTC, merged