defaults.{lua,js}: mark only wheel script-bindings as nonscalable
mpv-player/mpv pull request #15448
Opened 2024-12-07 13:31 UTC by guidocella

In mp.add_key_binding, prepend nonscalable only to wheel bindings which are the only ones that can be scalable. This is just a cosmetic change to not unnecessarily print nonscalable before every binding added with mp.add_key_binding in scripts that read input-bindings like stats.

AXIS_ aliases are not matched because they have been deprecated for 5 years since 1649ba15ab.

2024-12-07 13:50 UTC, avih commented
I disliked adding "nonscalable" to all binding by default from the begining, and It's probably a good thing to not add scalable to keys which don't support it anyway, but I don't think the knowledge about which keys these are belongs in defaults.lua/js. Same for other libmpv clients for that matter.

Without asking for this to happen, I think the best thing is to remove this code completely, make the default wheel bindings non-scalable in mpv itself (i.e. at the user's input.conf, `MOUSE_WHEEL foo` would be non-scalable), but make all the default wheel biding (i.e. at etc/input.conf at the source code) scalable.

This way users which didn't configure it themselves get scalable-by-default with new mpv, and users which did - can add `scalable` at their input.conf if they prefer, and if they don't know about it, then so be it - they'd keep having the same behavior they always had.

If all of you completely insist that "MOUSE_WHEEL foo` at the user's input.conf must be scalable by default, then you can add a property which reports the scalable key names, and then default.lua/js can check those instead of hardcoding "WHEEL", and then changing it whenever other keys become scalable.

2024-12-08 18:31 UTC, avih commented
I won't repeat my arguments, but I still dislike it.

2024-12-08 18:57 UTC, avih commented
> Adding a property just to not check WHEEL is overkill

This is not a preferred solution.

It's a suggestion to the address the incorrect approach that defaults.lua/js should not internally hold info about which keys can be scalable and which don't.

Another solution is to simply not make that distinction and skip this PR.

Another might be to add a flag to `define-section` which makes keys non-scalable by default.

You created this problem, be creative, and find a clean solution.

2024-12-08 19:10 UTC, guidocella commented
There is no list of keys that can be scalable, it's just wheel. This is already the clean solution because it just checks 1 string in 2 existing lines instead of unnecessarily adding new mechanisms.

2024-12-08 19:34 UTC, guidocella commented
Right but that's an emulation where you manually specifically a scale, it shouldn't matter for script-bindings.

2024-12-08 19:45 UTC, avih commented
> There is no list of keys that can be scalable

There is. Today it maybe contains only MOUSE_WHEEL, and tomorrow who knws.

While it's not a huge hack currently, it's still a hack, and It's not defaults.lua/js job to know these things.

2024-12-08 19:53 UTC, guidocella commented
These can be modified then instead of prematurely adding complexity that may never be needed. It's not like this a vital feature that's going to break mpv if more keys are added.

2024-12-08 19:54 UTC, guidocella commented
These can be modified then instead of prematurely adding complexity that may never be needed. It's not like this a vital feature that's going to break mpv if more keys are added.

2024-12-08 20:16 UTC, avih commented
> These can be modified then instead of prematurely adding complexity that may never be needed

This is how code becomes unmanagable.

> It's not like this a vital feature that's going to break mpv if more keys are added.

Great. So don't add it.

2024-12-10 13:40 UTC, guidocella commented
I just noticed this by adding a comment to input.c, doesn't `--input-preprocess-wheel=no` break high precision scaling? If so I need to remove it from the image profile.

2024-12-10 13:54 UTC, avih commented
I still think that adding a `define-section` flag of `default-scalable` or `default-noscale` or whatever to control the default behavior of the section instead of adding it to individual bindings is better, or, as mentioned, disable scalable by default at the mpv side.

But if you all insist that adding it to individual bindings is the best thing, then the last force-push with the comment at `input.c` is acceptable for me. Though I won't merge it myself.

2024-12-10 15:02 UTC, guidocella commented
The comment in the input.c didn't make sense since scalable keys are not listed there, or anywhere. VOs call `mp_input_put_wheel()` with a scale which passes it to `feed_key()`.

2024-12-10 19:33 UTC, avih approved these changes
Very good update to the docs, and good comments too. Many thanks.

2024-12-11 11:29 UTC, avih commented
Considering that the real motivation for this PR is to make the key-bindings page in `stats.lua` less noisy, I think a better alternative to the current code is to filter out `nonscalable` in `stats.lua` when the contitions match (I'm guessing when the command includes `script-binding` or `script-message-to`, and `WHEEL*` is not present, or whatever other method which seem appropriate).

This is only one place instead of two, it's only an informational display, where retouching the output for readability is acceptrable, and it doesn't require defaults.lua/js to know about a list of special keys which need custom handling - info which just doesn't belong there.

Also, if the scalable keys/commands combo ever changes and not updated accordingly at `stats.lua`, then only stats.lua would be incorrect, instead of scripts starting to behave incorrectly.

In such case, the docs commit should stay because it's great, and a comment can also be added at `stats.lua` about the cases which need filtering, but it's less important there than at defaults.lua/js.

So when this alternative exists, I'm removing my approval for the current code.

2024-12-11 11:30 UTC, avih requested changes
The custom handling should be implemented at `stats.lua`, rather than at defaults.lua/js.

2024-12-11 11:37 UTC, guidocella commented
stats.lua is not the only script that reads input-bindings. select.lua reads it and so do 3rd-party scripts like https://github.com/stax76/mpv-scripts?tab=readme-ov-file#command_palette

2024-12-11 12:07 UTC, avih commented
> stats.lua is not the only script that reads input-bindings. select.lua reads it and so do 3rd-party scripts like https://github.com/stax76/mpv-scripts?tab=readme-ov-file#command_palette

Citing yourself in quite a few occasions, it's only cosmetic and therefore non-critical in all those places, in contrast to maintaining it at defaults.lua/js, where it requires absolutely correct implementation, and can result in incorrect scripts behavior otherwise.

I'd imagine it's a very small function, probably one-liner split over 1-2 lines, to filter the command for the vast majority of cases (remove the first `nonscalable` if later at the command there's `-`/`_`-insentitive `script-binding` or `script-message-to`, and yet later at the command there's case-insensitive `WHEEL*`).

So this function can be duplicated where it's considered useful.

Or you can add it as a lua module if you think it's important to have a single implementation which various scripts can use. I don't, but I wouldn't mind it either.

But it just doesn't belong at defaults.lua/js, even if it's only a single line at each.

2024-12-15 09:39 UTC, avih commented
@guidocella do you plan to work on this?

I already came up with several ideas and you rejected all of them, and I don't have others currently, but I think specifically the last one is very viable - tiny function to add to stats and maybe console/input, and which can't break scripts if something changes down the line.

If you still don't like it, maybe you can come up with some alternatives yourself which we can assess?

Otherwise, if you don't want to consider anything other than making this change at defaults.lua/js, then let's close this PR, and we can reopen it, or file a new PR when we're ready.

2024-12-15 09:42 UTC, guidocella commented
It's not worth wasting any more time on this. Do whatever you want with the commits.

2024-12-15 09:42 UTC, closed without merging