ios/macos: Use non-exclusive audio session
mpv-player/mpv pull request #15506
Opened 2024-12-13 04:42 UTC by moffatman

Using this option means the OS  won't pause other
sources of audio when playback starts in MPV.

This matches the behaviour on other platforms.

2024-12-13 12:52 UTC, moffatman commented
updated the commit with desired capitalization

2024-12-13 13:14 UTC, llyyr commented
mpv has `--audio-exclusive` so the option should preferably be mapped to this AO.

2024-12-13 16:05 UTC, moffatman commented
Good point, added it

2024-12-14 12:31 UTC, Akemi commented
the commit prefix should be `ao_audiounit:`. also on a side note, currently seems to be iOS/tvOS/iPadOS only because of `kAudioUnitSubType_RemoteIO` (https://developer.apple.com/documentation/audiotoolbox/kaudiounitsubtype_remoteio?language=objc). so no macOS support.

https://github.com/mpv-player/mpv/blob/e52f975842196e1581299312b9c160aa16c81d04/meson.build#L811-L817

this change should also update the corresponding manual entry for `--audio-exclusive`
https://github.com/mpv-player/mpv/blob/e52f975842196e1581299312b9c160aa16c81d04/DOCS/man/options.rst?plain=1#L2000-L2007

a bit OCD, in the commit message there is a double space between `OS  won't`.

pinging @tmm1 since he did the initial implementation. i also lack any device to test this on.

2024-12-14 12:33 UTC, Akemi requested changes
see above.

2024-12-14 20:37 UTC, moffatman commented
Sure, updated, I just tested it on iOS only, and assumed it was macOS too. Which I guess must use coreaudio?

2024-12-14 20:53 UTC, tmm1 commented
seems reasonable 👍🏼

2024-12-21 15:32 UTC, Akemi commented
still missing:
- additions to the documentation
- removal of the unnecessary comment

besides this it LGTM, though untested.

2024-12-22 02:50 UTC, moffatman commented
Can you give me a hint towards the documentation

2024-12-22 03:55 UTC, llyyr commented
https://github.com/mpv-player/mpv/blob/d82701962f99051a18d65c215b70d41ebadd9a22/DOCS/man/options.rst?plain=1#L2000-L2007

Add this audio output to the list

2024-12-23 13:45 UTC, Akemi approved these changes

2024-12-23 13:50 UTC, Akemi commented
one thing that came to mind. this changes the previous default behaviour of `audiounit`, eg it was always exclusive before and now is always none exclusive. should we document that in our https://github.com/mpv-player/mpv/tree/master/DOCS/interface-changes? i am leaning to yes.

pinging @Dudemanguy and @kasper93 since i am not sure.

2024-12-24 15:03 UTC, Akemi commented
can you please change the commit message+body to something like and rebase your branch.

```
ao_audiounit: add support for --audio-exclusive option

this changes the new default to non-exclusive.
```

2024-12-27 20:35 UTC, Dudemanguy commented
>should we document that

I would say yes.

2024-12-28 12:36 UTC, Akemi commented
then one last thing please. add a text file `audiounit-exclusive.txt` (or similar) here https://github.com/mpv-player/mpv/tree/master/DOCS/interface-changes with content similar to `add --audio-exclusive option support for ao=audiounit and make non-exclusive the new default`.

2024-12-31 12:51 UTC, merged

2024-12-31 12:51 UTC, Akemi commented
thank you for the contribution and your patience.