osdep: add compile time option to default to xdg
mpv-player/mpv pull request #8024
Opened 2020-08-23 16:33 UTC by LaserEyess

This commit adds a `--enable-xdg` configure flag that will switch
the order mpv looks for configurations by default. Instead of
looking in `$HOME/.mpv` first, it will check `$XDG_CONFIG_DIR/mpv`.

This is disabled by default.

2020-08-23 18:47 UTC, wm4 requested changes
I don't think it's expected that "home" can return something empty, like it seems to be possible here.

2020-08-23 18:53 UTC, emanuele6 commented
Why do you use a runtime check for a compile time option?

2020-08-23 19:15 UTC, LaserEyess commented
@emanuele6 the compiler will optimize that ternary operation to the correct result since it knows HAVE_XDG is always defined as true. It is just slightly more elegant than doing preprocessor stuff.

2020-08-23 19:23 UTC, emanuele6 commented
I know that most compilers are likely to optimise this, but writing the code this way will probably make the code harder to further optimise for the compiler.

Also this is really not "elegant" to my eyes since it's just obfuscating information for no reason.

If this method is used in other places in the code base, I won't complain further though.

2020-08-23 19:54 UTC, LaserEyess commented
I don't see how this makes the code harder to optimize, do you have any examples? Again this could all be redone with preprocessor conditionals and it should amount to the exact same thing. I'm not an expert on C or compilers so if you have a reason why it should be done that way due to how gcc/clang/etc optimize code please let me know.

2020-08-23 20:44 UTC, wm4 commented
That attempt duplicates some code and makes a mess of the meaning of the variables...
Please keep it simple and correct.

2020-08-24 14:54 UTC, LaserEyess commented
I had hoped to do this without some weird preprocessor thing but I am not smart enough to do that, so I used an implementation that just switches the variables based on `HAVE_XDG`. I cannot think of a way to do this intelligently without a bunch of string copies or something. The variable name changes reflect the intended purpose of each, so that abstracting them to `MPV_HOME` and `OLD_HOME` defines makes more sense in this context.

2020-10-06 11:53 UTC, wm4 commented
I'm rejecting this.

2020-10-06 11:53 UTC, closed without merging