command: add delete-watch-later-config
mpv-player/mpv pull request #8199
Opened 2020-10-22 16:42 UTC by CyberShadow

```
This introduces the delete-watch-later-config command, to complement
write-watch-later-config. This is an alternative to #8141.

The general problem that this change is attempting to help solve has
been described in #336, #3169 and #6574. Though persistent playback
position of a single file is generally a solved problem, this is not
the case for playlists, as described in #8138.

The motivation is facilitating intermittent playback of very large
playlists, consisting of hundreds of entries each many hours
long. Though the current "watch later" mechanism works well - provided
that the files each occur only once in that playlist, and are played
only via that playlist - the biggest issue is that the position is
lost completely should mpv exit uncleanly (e.g. due to a power
failure).  Existing workarounds (in the form of Lua scripts which call
write-watch-later-config periodically) fail in the playlist case, due
to the mechanism used by mpv to determine where within a playlist to
resume playback from.

The missing puzzle piece needed to allow scripts to implement a
complete solution to this problem is simply a way to clean up the
watch-later configuration that the script asked mpv to write using
write-watch-later-config. With that in place, scripts can then
register an end-file event listener, check the stop playback reason,
and in the "eof" and "stop" case, invoke delete-watch-later-config to
delete any saved positions written by write-watch-later-config. The
script can then proceed to immediately write a new one when the next
file is loaded, which altogether allows mpv to resume from the correct
playlist and file position upon next startup.

Because events are delivered and executed asynchronously,
delete-watch-later-config takes an optional filename argument, to
allow scripts to clear watch-later configuration for files after mpv
had already moved on from playing them and proceeded to another file.

A Lua script which makes use of this change can be found here:
https://gist.github.com/CyberShadow/2f71a97fb85ed42146f6d9f522bc34ef
(A modification of the one written by @Hakkin, in that this one takes
advantage of the new command, and also saves the state immediately
when a new file is loaded.)
```

2020-10-22 16:47 UTC, Dudemanguy approved these changes

2020-10-22 16:47 UTC, Dudemanguy commented
LGTM

2020-10-22 19:09 UTC, Dudemanguy requested changes
Oops, I just realized that the "filename" flag here isn't optional like it should be. Missed that on the first pass.

2020-10-22 19:13 UTC, CyberShadow commented
Oops, thanks for catching that. FIxed.

2020-10-22 19:32 UTC, Dudemanguy commented
Also the char * isn't empty, it's `""`.

2020-10-22 19:38 UTC, CyberShadow commented
When the command is parsed as a string? Strange but OK. I added a check.

2020-10-22 19:41 UTC, Dudemanguy commented
Oh sorry, I meant `cmd->args[0].v.s` is `""` if the filename flag isn't specified.

2020-10-22 19:43 UTC, CyberShadow commented
That's how I understood it too, but that only seems to be the case when the command is invoked via `mp.command` or `input.conf`. With `mp.commandv`, it's `NULL`.

2020-10-22 19:52 UTC, Dudemanguy commented
Ah glad you caught that. I suppose this is the best way after all. Anyways, works just fine now. Thanks

2020-10-22 19:53 UTC, merged

2020-10-23 04:15 UTC, CyberShadow commented
Thank you for the review and your help in figuring out the best solution here :)