win32: take dpi scale into account with [current-]window-scale
mpv-player/mpv pull request #9104
Opened 2021-08-09 19:36 UTC by avih

win32: take dpi scale into account with [current-]window-scale (osx/x11/wayland already do that), and two minor refinements:
- Ensure initial dpi-scale value.
- Support the property `display-hidpi-scale` (only used from `console.lua`).

2021-08-16 22:10 UTC, jeeb requested changes
In general looks good to me, just some notes on `update_dpi` and something regarding visual positioning with the multiplication.

Since dpi_scale does not get changed in case of `hidpi_window_scale` being a falsie, this /should/ also not really break things as I do not see `VOCTRL_SET_UNFS_WINDOW_SIZE` being commanded in unrelated places.

2021-08-16 22:10 UTC, jeeb commented on video/out/w32_common.c
> +    if (w32->dpi_scale <= 0)
Also I do wonder how likely it is that after [`GetDpiForMonitor`](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor) returns `S_OK`, you get garbage values... It seems like Windows moved from plainly querying from drivers to having its own calculation logic with the WDDM (via [here](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getdevicecaps)):

> Unfortunately, a display driver that is implemented to the Windows Display Driver Model (WDDM) (introduced in Windows Vista) causes GDI to not get the info, so GetDeviceCaps must always calculate the info.

Basically just tired and wondering if the goto'd forced checking is really required or not :P (and whether you have any real suspicions with regards to `GetDeviceCaps` or so, or if this is just forcing a check on everything).

2021-08-16 22:23 UTC, avih commented on video/out/w32_common.c
> +    if (w32->dpi_scale <= 0)
> Also I do wonder how likely it is that after [`GetDpiForMonitor`](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor) returns `S_OK`, you get garbage values...

> Basically just tired and wondering if the goto'd forced checking is really required or not

I have no reason to suspect garbage values. However, the following commit divides by this value, so it's a safety measure to ensure that no matter what - we never divide by 0.

> If dpi_scale ended up invalid then dpi from which it was calculated most likely ended up such as well. If this is done, the logic would look pretty similar to the else case just before.

You mean adding something like this?
```c
if (w32->dpi <= 0)
    w32->dpi = 96;
```

I'd be fine with that.

2021-08-16 22:25 UTC, avih commented on video/out/w32_common.c
> +        s[0] *= w32->dpi_scale;
Sure. Will do.

2021-08-17 23:21 UTC, avih commented
Addressed both comments, as well as additional comments given on IRC (at the first commit - refactor `update_dpi()` to remove duplications and improve clarity).

Thanks for the review.

2021-08-17 23:21 UTC, merged

2022-01-25 13:35 UTC, ValZapod commented
Do you know how to overwrite "DPI detected from the new API" for HDMI display in mpv and systemwide?? My LG C9 of 55 reports 77' in EDID. Crazy.